import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import { createClient } from '@supabase/supabase-js';

const __filename=fileURLToPath(import.meta.url), __dirname=path.dirname(__filename), PORT=3000;
const app=express(); app.use(express.json());
type Role='admin'|'viewer'; type Status='pending'|'completed'; type Brand='mio_beauty'|'mio_home'; type Type='barter'|'paid';
interface History{id:string;date:string;collaborationType:Type;brand:Brand;status:Status;createdAt:string;completedAt?:string|null;manager?:string}
interface Blogger{id:string;nickname:string;date:string;collaborationType:Type;brand:Brand;status:Status;createdAt:string;completedAt?:string|null;manager?:string;history:History[]}
const DATA_FILE=path.join(__dirname,'data','bloggers.json');
const supabaseKey=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_PUBLISHABLE_KEY; const supabase=supabaseKey&&process.env.SUPABASE_URL?createClient(process.env.SUPABASE_URL,supabaseKey):null;
const normalize=(n:string)=>`@${String(n||'').trim().replace(/^@+/,'')}`;
const rowToBlogger=(r:any):Blogger=>({id:r.id,nickname:r.nickname,date:r.date,collaborationType:r.collaboration_type,brand:r.brand,status:r.status,createdAt:r.created_at||new Date().toISOString(),completedAt:r.completed_at||null,manager:r.manager||undefined,history:Array.isArray(r.history)?r.history:[]});
const bloggerToRow=(b:Blogger)=>({id:b.id,nickname:b.nickname,date:b.date,collaboration_type:b.collaborationType,brand:b.brand,status:b.status,created_at:b.createdAt,completed_at:b.completedAt||null,manager:b.manager||null,history:b.history||[]});
function localRead():Blogger[]{try{if(!fs.existsSync(DATA_FILE))return [];const raw=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));const map=new Map<string,Blogger>();for(const item of raw){const nick=normalize(item.nickname);const key=nick.slice(1).toLowerCase();const history=Array.isArray(item.history)&&item.history.length?item.history:[{id:`${item.id}-initial`,date:item.date,collaborationType:item.collaborationType||'barter',brand:item.brand||'mio_beauty',status:item.status||'completed',createdAt:item.createdAt||new Date().toISOString(),completedAt:item.completedAt||null,manager:item.manager}];if(!map.has(key))map.set(key,{...item,nickname:nick,history});else{const existing=map.get(key)!;for(const h of history)if(!existing.history.some(x=>x.id===h.id))existing.history.push(h)}}return [...map.values()]}catch{return []}}
function localWrite(data:Blogger[]){fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});fs.writeFileSync(DATA_FILE,JSON.stringify(data,null,2))}
async function readBloggers(){if(!supabase)return localRead();const {data,error}=await supabase.from('bloggers').select('*').order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(rowToBlogger)}
async function writeBloggers(data:Blogger[]){if(!supabase)return localWrite(data);const {error}=await supabase.from('bloggers').upsert(data.map(bloggerToRow),{onConflict:'id'});if(error)throw error}
const credentials:{username:string;password:string;role:Role}[]=[{username:'jamshid',password:'123',role:'admin'},{username:'nuriddin',password:'12345',role:'viewer'}];
function parseAuth(req:Request){const value=req.headers.authorization||'';if(!value.startsWith('Bearer '))return null;try{const decoded=Buffer.from(value.slice(7),'base64').toString('utf8');const [username,role]=decoded.split(':');return credentials.find(c=>c.username===username&&c.role===role)||null}catch{return null}}
function auth(requiredRole?:Role){return(req:Request,res:Response,next:NextFunction)=>{const user=parseAuth(req);if(!user)return res.status(401).json({success:false,error:'Tizimga kirish talab qilinadi.'});if(requiredRole==='admin'&&user.role!=='admin')return res.status(403).json({success:false,error:'Bu amal faqat admin uchun.'});(req as any).user=user;next()}}
const error=(res:Response,status:number,message:string)=>res.status(status).json({success:false,error:message});
app.post('/api/auth/login',(req,res)=>{const found=credentials.find(c=>c.username===String(req.body?.username||'').trim().toLowerCase()&&c.password===String(req.body?.password||''));if(!found)return error(res,401,'Login yoki parol xato.');const token=Buffer.from(`${found.username}:${found.role}`).toString('base64');res.json({success:true,session:{username:found.username,role:found.role,token}})});
app.get('/api/bloggers',auth(),async(_req,res)=>{try{res.json({success:true,data:await readBloggers()})}catch(e){console.error(e);error(res,500,'Ma’lumotlarni yuklashda xatolik yuz berdi.')}});
app.post('/api/bloggers',auth('admin'),async(req,res)=>{try{const {nickname,date,collaborationType,brand,manager}=req.body||{};if(!nickname?.trim())return error(res,400,"Bloger nickname'ini kiriting.");if(!date)return error(res,400,'Sanani tanlang.');const type:Type=['barter','paid'].includes(collaborationType)?collaborationType:'barter';const br:Brand=['mio_beauty','mio_home'].includes(brand)?brand:'mio_beauty';const normalized=normalize(nickname), key=normalized.slice(1).toLowerCase(), bloggers=await readBloggers(), now=new Date().toISOString();const history:History={id:`collab_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,date,collaborationType:type,brand:br,status:'pending',createdAt:now,completedAt:null,manager:manager?.trim()||undefined};const index=bloggers.findIndex(b=>b.nickname.slice(1).toLowerCase()===key);if(index>=0){const b=bloggers[index];b.history=[history,...(b.history||[])];Object.assign(b,{date,collaborationType:type,brand:br,status:'pending',completedAt:null,manager:manager?.trim()||undefined});await writeBloggers(bloggers);return res.json({success:true,data:b,isRepeat:true})}const b:Blogger={id:`b_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,nickname:normalized,date,collaborationType:type,brand:br,status:'pending',createdAt:now,completedAt:null,manager:manager?.trim()||undefined,history:[history]};bloggers.unshift(b);await writeBloggers(bloggers);res.status(201).json({success:true,data:b,isRepeat:false})}catch(e){console.error(e);error(res,500,'Blogerni saqlashda xatolik yuz berdi.')}});
app.patch('/api/bloggers/:id/complete',auth('admin'),async(req,res)=>{try{const data=await readBloggers(),b=data.find(x=>x.id===req.params.id);if(!b)return error(res,404,'Bloger topilmadi.');const now=new Date().toISOString();b.status='completed';b.completedAt=now;b.history.forEach(h=>{if(h.status==='pending'){h.status='completed';h.completedAt=now}});await writeBloggers(data);res.json({success:true,data:b})}catch(e){console.error(e);error(res,500,'Blogerni yangilashda xatolik yuz berdi.')}});
app.delete('/api/bloggers/:id',auth('admin'),async(req,res)=>{try{const data=await readBloggers(),next=data.filter(x=>x.id!==req.params.id);if(next.length===data.length)return error(res,404,'Bloger topilmadi.');await writeBloggers(next);res.json({success:true})}catch(e){console.error(e);error(res,500,'Blogerni o‘chirishda xatolik yuz berdi.')}});
async function start(){if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}else{const dist=path.join(process.cwd(),'dist');app.use(express.static(dist));app.get('*',(_req,res)=>res.sendFile(path.join(dist,'index.html')))}app.listen(PORT,'0.0.0.0',()=>console.log(`MIO server running on ${PORT}`))}start();
