import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Activity, ArrowDownToLine, ArrowUpFromLine, BarChart3, Bell, Check, ChevronDown,
  ClipboardList, Download, FileText, Filter, GripVertical, LayoutGrid, List,
  Menu, Moon, MoreHorizontal, PackageCheck, Palette, PanelLeft, Plus, RefreshCw,
  Search, Settings2, SlidersHorizontal, Sparkles, Sun, Trash2, Upload, UserRound,
  Users, X, Zap
} from 'lucide-react';
import { Blogger, BrandType, CollaborationType } from '../types';
import { AddBloggerModal } from './AddBloggerModal';

const coral = '#F0826D';
const stages = [
  { id: 'new', label: 'Yangi', color: '#7c83fd' },
  { id: 'working', label: 'Ishlanmoqda', color: '#f59e0b' },
  { id: 'waiting', label: 'Kontent kutilmoqda', color: '#a78bfa' },
  { id: 'review', label: 'Tekshiruvda', color: '#38bdf8' },
  { id: 'done', label: 'Yakunlangan', color: '#34d399' },
] as const;
type Stage = typeof stages[number]['id'];
type ViewMode = 'table' | 'kanban';

const stageFor = (b: Blogger): Stage => b.status === 'completed' ? 'done' : ((b as any).stage || 'working');
const avatarColor = (name: string) => {
  const colors = ['#ef8b78', '#857df3', '#45b7a7', '#f3ae54', '#5c9be8', '#c17ee8'];
  return colors[Math.abs([...name].reduce((a, c) => a + c.charCodeAt(0), 0)) % colors.length];
};
const initials = (name: string) => name.replace('@', '').slice(0, 2).toUpperCase();
const fmt = (value: number) => new Intl.NumberFormat('uz-UZ', { notation: 'compact', maximumFractionDigits: 1 }).format(value);

interface Props {
  bloggers: Blogger[];
  onOpenAddModal: () => void;
  onAddBlogger: (data: any) => Promise<boolean>;
  onCompleteBlogger: (id: string) => void;
  onReopenBlogger: (id: string) => void;
  onDeleteBlogger: (id: string) => void;
  onRefresh: () => void;
  onOpenSettings?: () => void;
}

export const MioMonitoringDashboard: React.FC<Props> = ({ bloggers, onOpenAddModal, onAddBlogger, onCompleteBlogger, onReopenBlogger, onDeleteBlogger, onRefresh }) => {
  const [view, setView] = useState<ViewMode>('table');
  const [query, setQuery] = useState('');
  const [stageFilter, setStageFilter] = useState<'all' | Stage>('all');
  const [brandFilter, setBrandFilter] = useState<'all' | BrandType>('all');
  const [selected, setSelected] = useState<Blogger | null>(null);
  const [resultFor, setResultFor] = useState<Blogger | null>(null);
  const [mobileNav, setMobileNav] = useState('bloggers');
  const [theme, setTheme] = useState<'light' | 'dark' | 'system'>('light');
  const [compact, setCompact] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [toast, setToast] = useState('');
  const importRef = useRef<HTMLInputElement>(null);

  const filtered = useMemo(() => bloggers.filter(b => {
    const q = query.toLowerCase().trim();
    const matches = !q || [b.nickname, b.category, b.manager, b.notes].filter(Boolean).some(x => String(x).toLowerCase().includes(q));
    return matches && (stageFilter === 'all' || stageFor(b) === stageFilter) && (brandFilter === 'all' || b.brand === brandFilter) && !b.isBlacklisted;
  }), [bloggers, query, stageFilter, brandFilter]);
  const activeCount = bloggers.filter(b => stageFor(b) !== 'done' && !b.isBlacklisted).length;
  const totalAudience = bloggers.reduce((sum, b) => sum + (parseInt(String(b.audience || '0').replace(/\D/g, ''), 10) || 0), 0);

  useEffect(() => {
    const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); document.getElementById('blogger-search')?.focus(); } if (e.key === 'Escape') { setSelected(null); setResultFor(null); setSettingsOpen(false); } };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, []);
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 2600); return () => clearTimeout(t); } }, [toast]);

  const move = (id: string, stage: Stage) => { setToast(`Hamkorlik “${stages.find(s => s.id === stage)?.label}” bosqichiga o‘tkazildi`); if (stage === 'done') onCompleteBlogger(id); };
  const exportCsv = () => {
    const rows = [['Nickname', 'Kategoriya', 'Brend', 'Status', 'Obunachilar', 'Menejer'], ...filtered.map(b => [b.nickname, b.category || '', b.brand, stages.find(s => s.id === stageFor(b))?.label || '', b.audience || '', b.manager || ''])];
    const blob = new Blob([rows.map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `mio-bloggerlar-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); URL.revokeObjectURL(a.href); setToast('CSV hisobot yuklab olindi');
  };
  const importCsv = (file?: File) => { if (!file) return; setToast(`${file.name} import uchun qabul qilindi`); };

  return <div className={`${theme === 'dark' ? 'dark' : ''} min-h-screen bg-[#f5f6fb] text-slate-900 dark:bg-[#171824] dark:text-white`}>
    <aside className="hidden lg:flex fixed inset-y-0 left-0 z-20 w-[238px] flex-col border-r border-slate-200/80 bg-white/90 px-5 py-6 dark:border-white/10 dark:bg-[#1d1e2b]">
      <div className="flex items-center gap-3 px-2 mb-10"><div className="h-10 w-10 rounded-2xl bg-[#f7b2a3] flex items-center justify-center text-white font-black text-xl">m</div><div><b className="text-lg tracking-tight">MIO</b><p className="text-[10px] text-slate-400 font-bold uppercase tracking-[.2em]">Blogger Hub</p></div></div>
      <p className="px-3 mb-2 text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Ish maydoni</p>
      {[['bloggers', Users, 'Bloggerlar'], ['campaigns', ClipboardList, 'Hamkorliklar'], ['analytics', BarChart3, 'Analitika']].map(([id, Icon, label]: any) => <button key={id} onClick={() => setMobileNav(id)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition mb-1 ${mobileNav === id ? 'bg-[#fff0ed] text-[#e97560]' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-white/5'}`}><Icon className="h-4 w-4" />{label}</button>)}
      <div className="mt-auto space-y-1"><button onClick={() => setSettingsOpen(true)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-slate-50 dark:hover:bg-white/5"><Settings2 className="h-4 w-4" />Sozlamalar</button><div className="mt-4 rounded-2xl bg-slate-900 p-4 text-white"><Sparkles className="mb-3 h-5 w-5 text-[#f7b2a3]" /><b className="text-sm">MIO Pro</b><p className="mt-1 text-[11px] text-white/60">Hamkorliklarni aqlli boshqaring.</p></div></div>
    </aside>
    <main className="lg:pl-[238px]">
      <header className="sticky top-0 z-10 flex h-[76px] items-center justify-between border-b border-slate-200/70 bg-[#f5f6fb]/90 px-4 backdrop-blur-xl sm:px-8 dark:border-white/10 dark:bg-[#171824]/90"><div><p className="text-xs font-bold text-slate-400">Payshanba, 24 Sentabr 2026</p><h1 className="text-xl font-black tracking-tight">Blogger monitoring</h1></div><div className="flex items-center gap-2"><button className="hidden h-10 w-10 items-center justify-center rounded-xl bg-white text-slate-500 shadow-sm sm:flex dark:bg-white/10"><Bell className="h-4 w-4" /></button><button onClick={() => setSettingsOpen(true)} className="flex h-10 items-center gap-2 rounded-xl bg-white px-3 text-xs font-bold shadow-sm dark:bg-white/10"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#f7b2a3] text-[10px] font-black text-white">JD</span><span className="hidden sm:inline">Jamshid</span><ChevronDown className="h-3.5 w-3.5 text-slate-400" /></button></div></header>
      <div className="mx-auto max-w-[1440px] px-4 py-5 sm:px-8 sm:py-8">
        <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat icon={Users} label="Jami bloggerlar" value={bloggers.length} tint="violet" /><Stat icon={Zap} label="Faol hamkorliklar" value={activeCount} tint="amber" /><Stat icon={Activity} label="O‘rtacha engagement" value="6.8%" tint="blue" /><Stat icon={BarChart3} label="Jami auditoriya" value={`${fmt(totalAudience)}+`} tint="green" /></div>
        <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black tracking-tight">Bloggerlar</h2><p className="mt-1 text-sm text-slate-400">Barcha hamkorliklarni bir joyda kuzating</p></div><div className="flex items-center gap-2"><button onClick={exportCsv} className="hidden h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600 shadow-sm hover:border-slate-300 sm:flex dark:border-white/10 dark:bg-white/5 dark:text-white"><Download className="h-4 w-4" />Export</button><button onClick={onOpenAddModal} className="flex h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 text-xs font-bold text-white shadow-lg shadow-slate-900/15 hover:bg-slate-800 sm:flex-none"><Plus className="h-4 w-4" />Blogger qo‘shish</button></div></div>
        <div className="mb-4 flex flex-col gap-3 rounded-2xl border border-slate-200/80 bg-white p-3 shadow-sm dark:border-white/10 dark:bg-white/5 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input id="blogger-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Blogger, kategoriya yoki menejer bo‘yicha qidiring..." className="h-10 w-full rounded-xl bg-slate-50 pl-10 pr-10 text-xs font-semibold outline-none ring-[#f7b2a3] focus:ring-2 dark:bg-white/5" /><kbd className="absolute right-3 top-2.5 hidden rounded bg-white px-1.5 py-1 text-[10px] text-slate-400 shadow-sm sm:block">⌘ K</kbd></div><button onClick={() => setFiltersOpen(!filtersOpen)} className={`flex h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-bold ${filtersOpen || stageFilter !== 'all' || brandFilter !== 'all' ? 'bg-[#fff0ed] text-[#e97560]' : 'bg-slate-50 text-slate-500 dark:bg-white/5'}`}><SlidersHorizontal className="h-4 w-4" />Filter</button><div className="hidden items-center rounded-xl bg-slate-50 p-1 dark:bg-white/5 sm:flex"><button onClick={() => setView('table')} className={`rounded-lg p-2 ${view === 'table' ? 'bg-white text-slate-900 shadow-sm dark:bg-white/10 dark:text-white' : 'text-slate-400'}`}><List className="h-4 w-4" /></button><button onClick={() => setView('kanban')} className={`rounded-lg p-2 ${view === 'kanban' ? 'bg-white text-slate-900 shadow-sm dark:bg-white/10 dark:text-white' : 'text-slate-400'}`}><LayoutGrid className="h-4 w-4" /></button></div></div>
        {filtersOpen && <div className="mb-4 flex flex-wrap items-center gap-2 rounded-2xl bg-white p-3 shadow-sm dark:bg-white/5"><span className="mr-1 text-xs font-black text-slate-400">Bosqich:</span>{[['all', 'Barchasi'], ...stages.map(s => [s.id, s.label])].map(([id, label]) => <button key={id} onClick={() => setStageFilter(id as any)} className={`rounded-lg px-3 py-2 text-[11px] font-bold ${stageFilter === id ? 'bg-slate-900 text-white' : 'bg-slate-50 text-slate-500 dark:bg-white/5'}`}>{label}</button>)}<span className="ml-2 mr-1 text-xs font-black text-slate-400">Brend:</span>{[['all', 'Barchasi'], ['mio_beauty', 'MIO Beauty'], ['mio_home', 'MIO Home']].map(([id, label]) => <button key={id} onClick={() => setBrandFilter(id as any)} className={`rounded-lg px-3 py-2 text-[11px] font-bold ${brandFilter === id ? 'bg-[#fff0ed] text-[#e97560]' : 'bg-slate-50 text-slate-500 dark:bg-white/5'}`}>{label}</button>)}</div>}
        {view === 'table' ? <TableView bloggers={filtered} compact={compact} onSelect={setSelected} onResult={setResultFor} onDelete={onDeleteBlogger} /> : <KanbanView bloggers={filtered} onSelect={setSelected} onMove={move} />}
        {filtered.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center dark:border-white/10 dark:bg-white/5"><Users className="mx-auto mb-3 h-8 w-8 text-slate-300" /><b className="text-sm">Bloggerlar topilmadi</b><p className="mt-1 text-xs text-slate-400">Filterlarni o‘zgartirib ko‘ring yoki yangi blogger qo‘shing.</p></div>}
      </div>
    </main>
    <nav className="fixed bottom-0 left-0 right-0 z-20 flex items-center justify-around border-t border-slate-200 bg-white/95 px-4 py-2 backdrop-blur-xl lg:hidden dark:border-white/10 dark:bg-[#1d1e2b]/95"><button onClick={() => setMobileNav('bloggers')} className="flex flex-col items-center gap-1 p-2 text-[10px] font-bold text-[#e97560]"><Users className="h-5 w-5" />Bloggerlar</button><button onClick={() => setView(view === 'table' ? 'kanban' : 'table')} className="flex flex-col items-center gap-1 p-2 text-[10px] font-bold text-slate-400"><LayoutGrid className="h-5 w-5" />Kanban</button><button onClick={() => setSettingsOpen(true)} className="flex flex-col items-center gap-1 p-2 text-[10px] font-bold text-slate-400"><Settings2 className="h-5 w-5" />Sozlamalar</button></nav>
    <button onClick={onOpenAddModal} className="fixed bottom-20 right-5 z-20 flex h-14 w-14 items-center justify-center rounded-full bg-[#f7b2a3] text-white shadow-xl shadow-[#f7b2a3]/40 lg:hidden"><Plus className="h-6 w-6" /></button>
    {selected && <ProfileDrawer blogger={selected} onClose={() => setSelected(null)} onResult={() => setResultFor(selected)} onDelete={() => { onDeleteBlogger(selected.id); setSelected(null); }} />}
    {resultFor && <ResultsModal blogger={resultFor} onClose={() => setResultFor(null)} onSave={() => { setResultFor(null); setToast('Hamkorlik natijalari saqlandi'); }} />}
    {settingsOpen && <SettingsModal theme={theme} setTheme={setTheme} compact={compact} setCompact={setCompact} onClose={() => setSettingsOpen(false)} onExport={exportCsv} onImport={() => importRef.current?.click()} onRefresh={onRefresh} />}
    <input ref={importRef} type="file" accept=".csv" className="hidden" onChange={e => importCsv(e.target.files?.[0])} />
    {toast && <div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold text-white shadow-xl">{toast}</div>}
  </div>;
};

const Stat = ({ icon: Icon, label, value, tint }: any) => <div className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-white/5"><div className={`mb-3 flex h-8 w-8 items-center justify-center rounded-lg ${tint === 'amber' ? 'bg-amber-50 text-amber-500' : tint === 'blue' ? 'bg-sky-50 text-sky-500' : tint === 'green' ? 'bg-emerald-50 text-emerald-500' : 'bg-violet-50 text-violet-500'}`}><Icon className="h-4 w-4" /></div><p className="text-[11px] font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>;

const TableView = ({ bloggers, compact, onSelect, onResult, onDelete }: any) => <div className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-white/10 dark:bg-white/5"><div className="hidden grid-cols-[2fr_1.5fr_1fr_1fr_1fr_auto] gap-4 border-b border-slate-100 px-5 py-3 text-[10px] font-black uppercase tracking-wider text-slate-400 md:grid dark:border-white/10"><span>Blogger</span><span>Kategoriya</span><span>Auditoriya</span><span>Engagement</span><span>Bosqich</span><span /></div>{bloggers.map((b: Blogger) => <div key={b.id} onClick={() => onSelect(b)} className={`grid cursor-pointer grid-cols-1 gap-3 border-b border-slate-100 px-4 ${compact ? 'py-3' : 'py-4'} transition hover:bg-slate-50 md:grid-cols-[2fr_1.5fr_1fr_1fr_1fr_auto] md:items-center md:gap-4 md:px-5 dark:border-white/10 dark:hover:bg-white/5`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-xs font-black text-white" style={{ background: avatarColor(b.nickname) }}>{initials(b.nickname)}</div><div className="min-w-0"><p className="truncate text-sm font-black">{b.nickname}</p><p className="mt-0.5 truncate text-[11px] text-slate-400">{b.manager || 'Menejer biriktirilmagan'}</p></div></div><div className="hidden min-w-0 md:block"><p className="truncate text-xs font-bold">{b.category || '—'}</p><p className="mt-0.5 text-[10px] text-slate-400">{b.brand === 'mio_beauty' ? 'MIO Beauty' : 'MIO Home'}</p></div><div className="hidden text-xs font-bold md:block">{b.audience || '—'}</div><div className="hidden md:block"><span className="text-xs font-black">{(b as any).engagementRate || '6.8%'}</span><div className="mt-1 h-1 w-16 rounded-full bg-slate-100"><div className="h-1 rounded-full bg-[#f7b2a3]" style={{ width: `${Math.min(parseFloat((b as any).engagementRate || '6.8') * 10, 100)}%` }} /></div></div><div className="flex items-center justify-between md:block"><span className="rounded-lg px-2.5 py-1.5 text-[10px] font-black" style={{ background: `${stages.find(s => s.id === stageFor(b))?.color}18`, color: stages.find(s => s.id === stageFor(b))?.color }}>{stages.find(s => s.id === stageFor(b))?.label}</span><div className="flex gap-1 md:hidden"><button onClick={e => { e.stopPropagation(); onResult(b); }} className="rounded-lg bg-slate-50 px-2 py-1.5 text-[10px] font-bold text-slate-500">Natija</button><button onClick={e => { e.stopPropagation(); onDelete(b.id); }} className="rounded-lg bg-rose-50 p-1.5 text-rose-400"><Trash2 className="h-3.5 w-3.5" /></button></div></div><MoreHorizontal className="hidden h-4 w-4 text-slate-400 md:block" /></div>)}</div>;

const KanbanView = ({ bloggers, onSelect, onMove }: any) => <div className="flex gap-4 overflow-x-auto pb-4">{stages.map(stage => <div key={stage.id} className="min-w-[270px] flex-1 rounded-2xl bg-slate-100/80 p-3 dark:bg-white/5"><div className="mb-3 flex items-center justify-between px-1"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: stage.color }} /><b className="text-xs">{stage.label}</b><span className="rounded-md bg-white px-1.5 py-0.5 text-[10px] font-black text-slate-400 dark:bg-white/10">{bloggers.filter((b: Blogger) => stageFor(b) === stage.id).length}</span></div><MoreHorizontal className="h-4 w-4 text-slate-400" /></div>{bloggers.filter((b: Blogger) => stageFor(b) === stage.id).map((b: Blogger) => <div draggable onDragEnd={() => onMove(b.id, stage.id)} onClick={() => onSelect(b)} key={b.id} className="mb-3 cursor-grab rounded-xl border border-slate-200/80 bg-white p-3 shadow-sm active:cursor-grabbing dark:border-white/10 dark:bg-[#232433]"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg text-[10px] font-black text-white" style={{ background: avatarColor(b.nickname) }}>{initials(b.nickname)}</div><div><b className="text-xs">{b.nickname}</b><p className="text-[10px] text-slate-400">{b.audience || 'Auditoriya —'}</p></div></div><GripVertical className="h-4 w-4 text-slate-300" /></div><p className="mt-3 line-clamp-2 text-[11px] font-semibold text-slate-500">{b.notes || b.category || 'Hamkorlik tafsilotlari'}</p><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-2 text-[10px] text-slate-400 dark:border-white/10"><span>{b.date}</span><span className="font-black text-slate-700 dark:text-white">{(b as any).engagementRate || '6.8%'}</span></div></div>)}</div>)}</div>;

const ProfileDrawer = ({ blogger: b, onClose, onResult, onDelete }: any) => <div className="fixed inset-0 z-50"><div className="absolute inset-0 bg-slate-900/30 backdrop-blur-sm" onClick={onClose} /><aside className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl dark:bg-[#20212e] sm:p-8"><div className="mb-8 flex items-center justify-between"><span className="rounded-lg bg-[#fff0ed] px-2.5 py-1.5 text-[10px] font-black text-[#e97560]">BLOGGER PROFILI</span><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10"><X className="h-5 w-5" /></button></div><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl text-xl font-black text-white" style={{ background: avatarColor(b.nickname) }}>{initials(b.nickname)}</div><div><h2 className="text-xl font-black">{b.nickname}</h2><p className="text-xs text-slate-400">{b.category || 'Lifestyle blogger'}</p><div className="mt-2 flex gap-2 text-[10px] font-bold text-slate-400"><span>Instagram</span><span>Telegram</span><span>TikTok</span></div></div></div><div className="my-7 grid grid-cols-3 gap-2">{[['Obunachilar', b.audience || '—'], ['O‘rtacha ko‘rish', (b as any).avgViews || '48.2K'], ['Engagement', (b as any).engagementRate || '6.8%']].map(([l, v]) => <div className="rounded-xl bg-slate-50 p-3 dark:bg-white/5" key={l}><p className="text-[10px] font-bold text-slate-400">{l}</p><p className="mt-1 text-sm font-black">{v}</p></div>)}</div><div className="space-y-5"><Info label="Aloqa ma’lumotlari" value={b.manager ? `${b.manager} · manager@miouz.uz` : 'Aloqa ma’lumotlari kiritilmagan'} /><Info label="Kategoriya" value={b.category || 'Kategoriya belgilanmagan'} /><Info label="Ichki izohlar" value={b.notes || 'Izohlar yo‘q'} /><div><p className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-400">Hamkorliklar tarixi</p>{(b.history || []).slice(0, 3).map((h: any) => <div className="mb-2 flex items-center justify-between rounded-xl border border-slate-100 p-3 text-xs dark:border-white/10" key={h.id}><span className="font-bold">{h.category || 'Hamkorlik'}</span><span className="text-[10px] text-slate-400">{h.date}</span></div>)}</div></div><div className="mt-8 flex gap-2"><button onClick={onResult} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-slate-900 py-3 text-xs font-black text-white"><PackageCheck className="h-4 w-4" />Natija kiritish</button><button onClick={onDelete} className="rounded-xl bg-rose-50 px-4 text-rose-500"><Trash2 className="h-4 w-4" /></button></div></aside></div>;
const Info = ({ label, value }: any) => <div><p className="mb-1 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="text-xs font-bold text-slate-700 dark:text-slate-200">{value}</p></div>;

const ResultsModal = ({ blogger, onClose, onSave }: any) => <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl dark:bg-[#20212e] sm:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#e97560]">YAKUNIY NATIJA</p><h2 className="mt-1 text-xl font-black">{blogger.nickname} natijalari</h2></div><button onClick={onClose}><X className="h-5 w-5 text-slate-400" /></button></div><div className="grid grid-cols-2 gap-3">{['Post havolasi', 'Story/Post views', 'Like / comment', 'Reach', 'Engagement', 'Sotuv / promo-code'].map((label, i) => <label className={`${i === 0 ? 'col-span-2' : ''} text-[10px] font-black text-slate-500`} key={label}>{label}<input placeholder={i === 0 ? 'https://instagram.com/p/...' : i === 1 ? 'Masalan: 84 500' : 'Kiritish'} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-semibold outline-none focus:border-[#f7b2a3] dark:border-white/10 dark:bg-white/5" /></label>)}</div><label className="mt-4 block text-[10px] font-black text-slate-500">Yakuniy izoh<textarea rows={3} placeholder="Kontent va natija bo‘yicha izoh..." className="mt-1.5 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs outline-none focus:border-[#f7b2a3] dark:border-white/10 dark:bg-white/5" /></label><div className="mt-5 flex gap-2"><button onClick={onClose} className="flex-1 rounded-xl border border-slate-200 py-3 text-xs font-black text-slate-500 dark:border-white/10">Bekor qilish</button><button onClick={onSave} className="flex-1 rounded-xl bg-slate-900 py-3 text-xs font-black text-white">Natijani saqlash</button></div></div></div>;

const SettingsModal = ({ theme, setTheme, compact, setCompact, onClose, onExport, onImport, onRefresh }: any) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-[#20212e]"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">MIO SETTINGS</p><h2 className="mt-1 text-xl font-black">Theme va ma’lumotlar</h2></div><button onClick={onClose}><X className="h-5 w-5 text-slate-400" /></button></div><p className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-400">Ko‘rinish rejimi</p><div className="mb-5 grid grid-cols-3 gap-2">{[['light', Sun], ['dark', Moon], ['system', Palette]].map(([id, Icon]: any) => <button key={id} onClick={() => setTheme(id)} className={`flex flex-col items-center gap-2 rounded-xl border p-3 text-[10px] font-bold capitalize ${theme === id ? 'border-[#f7b2a3] bg-[#fff0ed] text-[#e97560]' : 'border-slate-200 text-slate-400'}`}><Icon className="h-4 w-4" />{id}</button>)}</div><div className="mb-5 flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-white/5"><div><b className="text-xs">Compact mode</b><p className="mt-1 text-[10px] text-slate-400">Jadval qatorlarini ixcham ko‘rsatish</p></div><button onClick={() => setCompact(!compact)} className={`h-6 w-11 rounded-full p-1 ${compact ? 'bg-[#f7b2a3]' : 'bg-slate-200'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${compact ? 'translate-x-5' : ''}`} /></button></div><div className="grid grid-cols-2 gap-2"><button onClick={onExport} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 py-3 text-xs font-black text-white"><ArrowDownToLine className="h-4 w-4" />CSV export</button><button onClick={onImport} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 py-3 text-xs font-black text-slate-600"><ArrowUpFromLine className="h-4 w-4" />CSV import</button></div><button onClick={() => window.print()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 py-3 text-xs font-black text-slate-600"><FileText className="h-4 w-4" />PDF hisobot / Print</button><button onClick={onRefresh} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-50 py-3 text-xs font-black text-slate-500"><RefreshCw className="h-4 w-4" />Ma’lumotlarni yangilash</button></div></div>;

export default MioMonitoringDashboard;
