import { Blogger, BrandType, CollaborationType, Session } from './types';
const KEY='mio_blogger_session';
const headers=()=>{const s=getAuth();return {'Content-Type':'application/json',...(s?.token?{Authorization:`Bearer ${s.token}`}:{})}};
export function getAuth():Session|null{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
export function logoutAuth(){localStorage.removeItem(KEY)}
export async function guestLoginApi():Promise<{success:boolean;session?:Session;error?:string}>{try{const r=await fetch('/api/auth/guest',{method:'POST',headers:{'Content-Type':'application/json'}});const j=await r.json();if(j.session)localStorage.setItem(KEY,JSON.stringify(j.session));return j}catch{return{success:false,error:'Server bilan bog‘lanib bo‘lmadi.'}}}
export async function loginApi(username:string,password:string):Promise<{success:boolean;session?:Session;error?:string}>{try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(j.session)localStorage.setItem(KEY,JSON.stringify(j.session));return j}catch{return{success:false,error:'Server bilan bog‘lanib bo‘lmadi. Ilova serveri ishlayotganini tekshiring.'}}}
export async function fetchBloggersApi():Promise<Blogger[]>{const r=await fetch('/api/bloggers',{headers:headers()});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ma’lumotlarni yuklashda xatolik yuz berdi.');return j.data||[]}
export async function addBloggerApi(data:{nickname:string;date:string;collaborationType:CollaborationType;brand:BrandType;manager?:string}){const r=await fetch('/api/bloggers',{method:'POST',headers:headers(),body:JSON.stringify(data)});return r.json() as Promise<{success:boolean;data?:Blogger;error?:string}>}
export async function completeBloggerApi(id:string){const r=await fetch(`/api/bloggers/${id}/complete`,{method:'PATCH',headers:headers()});return r.ok}
export async function updateBloggerApi(id:string,data:{nickname:string;date:string;collaborationType:CollaborationType;brand:BrandType;manager?:string}){const r=await fetch(`/api/bloggers/${id}`,{method:'PATCH',headers:headers(),body:JSON.stringify(data)});const j=await r.json();return {success:r.ok,error:j.error as string|undefined,data:j.data as Blogger|undefined}}
export async function deleteBloggerApi(id:string){try{const r=await fetch(`/api/bloggers/${id}`,{method:'DELETE',headers:headers()});const j=await r.json().catch(()=>({}));return {success:r.ok,error:j.error as string|undefined}}catch{return {success:false,error:'Server bilan bog‘lanib bo‘lmadi.'}}}
